services:
  keydb:
    image: redis:7-alpine
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 0s

  server:
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-nv",
          "-t1",
          "--spider",
          "http://127.0.0.1:8000/health"
        ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 0s
    env_file:
      - ../envs/server.env

  load-balancer:
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-nv",
          "-t=1",
          "--spider",
          "http://127.0.0.1:1337/health"
        ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 0s
    env_file:
      - ../envs/load-balancer.env

  client:
    restart: always

  nginx:
    image: nginx:1.25.3
    volumes:
      - /etc/ssl:/etc/ssl:ro
    restart: always
